# LISTAS SÃO MULTAVEIS, QUER DIZER QUE VOCÊ PODE ALTERAR O VALOR A QUALQUER MOMENTO.

# [] <- PARA MONTAR UMA LISTA.

# SE SUA LISTA JÁ TIVER VALORES E CASO VOCÊ QUEIRA ADICIONAR MAIS ALGUM VALOR USE O COMANDO APPEND(), ESSE NOVO ELEMENTO IRA SRR O ÚLTIMO ELEMENTO DA LISTA. 
EX: LANCHE.APPEND()

#PARA ADICIONAR UM ELEMENTO A LISTA, PORÉM QUEIRA QUE ELE VÁ PARA UMA POSIÇÃO ESPECIFICA, USE O COMANDO INSERT(POSIÇÃO, NOME DO ELEMENTO).
EX: LANCHE.INSERT(0, 'CACHORRO QUENTE')

#PARA APAGAR UM ELEMENTO DE UMA LISTA USE O COMANDO 'DEL NOME_LISTA[POSIÇÃO DO ITEM QUE IRA SER APAGADO]'.
EX: DEL LANCHE[3]

#COMANDO PARA APAGAR O ÚLTIMO ELEMENTO DE UMA LISTA USE O COMANDO 'NOME_LISTA.POP()'.
EX: LANCHE.POP()

#OUTRO COMANDO PARA APAGAR UM ELEMENTO DE UMA LISTA USANDO APENAS O NOME DO ELEMENTO USE O COMANDO 'NOME_LISTA.REMOVE(NOME DO ITEM QUE IRA SER APAGADO)'.
EX: LANCHE.REMOVE('PIZZA')

#PARA VERIFICAR SE O ITEM ESTÁ NA LISTA USE O COMANDO IF 'NOME_DO ITEM' IN 'NOME_LISTA:
EX: IF 'PIZZA' IN LANCHE:
        LANCHE.REMOVE('PIZZA')

#PARA CRIAR UMA LISTA ATRASVÉS DE RANGE.
EX: VALORES = LIST(RANGE(4,11)) #ESSE COMANDO IRA CRIAR UMA LISTA COM OS VALORES DE 4 ATÉ 10.

#PARA COLOCAR UMA LISTA EM ORDEM NÚMÉRICA USE O COMANDO SORT().
EX: VALORES = [8,2,5,4,9,3,0]
    VALORES.SORT()
#O NOVO VALOR DA LISTA SERÁ:
    VALORES = [0,2,3,4,5,8,9]

#OU SE CASO QUEIRA COLOCAR EM ORDEM NÚMÉRICA AO CONTRARIO USE O MESMO COMANDO E ADICIONE REVERSE = TRUE:
EX: VALORES = [8,2,5,4,9,3,0]
    VALORES.SORT(REVERSE=TRUE)
#O NOVO VALOR DA LISTA SERÁ:
    VALORES = [9,8,5,4,3,2,0]

#PARA CONTAR QUANTOS ELEMENTOS TEM NA LISTA USE O COMANDO LEN().
EX: VALORES = [8,2,5,4,9,3,0]
    LEN(VALORES)

#PARA FAZER UMA LIGAÇÃO DE LISTA:
EX: A = [1, 8, 5, 6]
    B = A

#PARA COPIAR UMA LISTA EM OUTRA:
EX: A = [1, 8, 5, 6]
    B = A[:]

-----------------------------------------------------------------------------------------------------------------

TESTE 1

valores = []
valores.append(5)
valores.append(7)
valores.append(9)
valores.append(5)
print(valores)

for c, v in enumerate(valores):
    print(f'Na posição {c} encontrei o valor {v}')

TESTE 2

valores = list()
for cont in range (1, 6):
    valores.append(int(input('Digite o {cont}º valor: ')))
print(valores)